### ISSUE TITLE
[Featrue] 통계, 정산 조회 API

### ISSUE THREAD

**Issue by younghyun-j** [younghyun-j/streaming-settlement#7]
> 💁‍♂️ GUIDE
> 1. 집중하기 위해 작은 단위로 진행하기
> 2. 하나의 이슈에 반영되는 PR 당 코드의 변경은 300줄이 넘어가지 않도록 노력하기

## 📝 Description
통계, 정산 조회 API

## ✅ TODO
- [ ] 통계 조회 API
  - [ ] 1일, 1주일, 1달 동안 조회수가 높은 동영상 TOP5
  - [ ] 1일, 1주일, 1달 동안 재생 시간이 긴 동영상 TOP5
- [ ] 정산 조회 API
  - [ ] 1일, 1주일, 1달 동안 총 정산금액, 영상별 정산금액, 광고별 정산금액을 영상별로 조회

## 💡 ETC
작업을 진행하면서 발생한 문제나 고려해야 할 기타 사항을 작성해주세요.
